### ISSUE TITLE
German Vowels not handled correctly ?

### ISSUE THREAD

**Issue by rivella50** [verhas/License3j#16]
Hi,
i just encoded a license file with a  German vowel (ä) as a feature value.
When loading the license file with

```
License lic = new License();
try {
  lic.loadKeyRingFromResource("license3j/pubring.gpg", digest);
  lic.setLicenseEncodedFromFile(licenseFileName);
} catch(Exception e) { }
```

and ask for that value i get back "Ã¤".
The plain license file is UTF-8.
Am i missing here something or could this be a bug of your tool ?

**Comment by verhas** [comment]
When a license is loaded from an encoded file the byte stream created by the decoding is converted to String using the platform default charset. Probably that is not utf-8 and that is the reason why you get the special characters.

As a side note: the method `setLicenseEncodedFromFile` is deprecated and will be removed from newer releases, but this has nothing to do with the issue.

I will modify the behaviour to use utf-8 instead of the default charset in the next release, which is not scheduled yet.

**Comment by rivella50** [comment]
So this means at the moment i cannot solve that problem by myself...
Using just UTF-8 probably also is not a good idea.
How about an overloaded License constructor (or the successor of setLicenseEncodedFromFile()) which uses per default the system charset and in a parameterized version the user can define it?

But at first it would be interesting if the problem with the German vowel also happens on your side.

**Comment by verhas** [comment]
If you look at the last commit diff you will see what causes the problem. I temporarily comitted into the source code change that makes the decoding to use utf-8.

The sample you provided and the analysis clearly leads to the conclusion that the default encoding on your machine is iso-latin-1. I see no point to reproduce the issue on my dev machine. And I also do not have the time.

**Comment by verhas** [comment]
I will consider your suggestion extending th API with overloaded methods.

**Comment by rivella50** [comment]
That would be nice, thank you!

**Comment by qqilihq** [comment]
I'm experiencing exactly the same issue. (for the records: my system's encoding is UTF-8).  The problem is obviously at this point in `License`:

```
/**
 * Set the license values from an input stream. The stream has to contain
 * properties.
 *
 * @param is
 *            the input stream to read the properties values from
 * @throws IOException
 *             when the input stream can not be read
 */
public void setLicense(final InputStream is) throws IOException {
	verified = false;
	licenseProperties = new Properties();
	licenseProperties.load(is);
}
```

`java.util.Properties.load(InputStream)` will always decode the InputStream using `ISO 8859-1` as stated in the JavaDoc. I solved that problem by overriding the `setLicense` method as follows and the umlauts decode just fine:

```
License license = new License() {
	@Override
	public void setLicense(InputStream is) throws IOException {
		// super implementation sets verified = false, but the field cannot be accessed here,
		// however, that doesn't seem to be an issue in my case, as the fields seems to get
		// set correctly through setLicenseEncoded anyways; do not call super, because
		// it will eat up the InputStream
		licenseProperties = new Properties();
		licenseProperties.load(new InputStreamReader(is, "utf-8"));
	}
};
```

**Comment by verhas** [comment]
new version 1.0.8 will contain the new methods and the old methods are deprecated
