### ISSUE TITLE
HardwareBinder giving different UUID

### ISSUE THREAD

**Issue by smolinacadena** [verhas/License3j#18]
I am using the HardwareBinder class to generate a UUID and include it in the license file generated by a license creator java app. Then I use this UUID to validate the license in the actual app. The problem is that the HardwareBinder class gives me a different UUID after some time. For example, the UUID is the same for two days then it changes. Also, there was a time when I restarted the computer and the UUID changed. What can this be related to? Is it maybe the OS? Has anybody had this problem before?

**Comment by truezjz** [comment]
Same issue here, the UUID changed after reboot,  any idea? 
I'm using Windows 7, JDK 1.7.

**Comment by verhas** [comment]
Since this is an operating system problem I close this issue. It seems that some operating systems and network drivers provide different information from time to time and thus the hardware binding can not be used reliably.

Since such a feature is also questionable the hardware binder is provided in the library as something that is there but is recommended not to be used, not only because of technical issues but also because of customer relationship problems.
