### ISSUE TITLE
Error when creating new license file

### ISSUE THREAD

**Issue by elmehdi-eljair** [verhas/License3j#23]
I'm trying to encode a new license file, but i got the following error : 

Exception in thread "main" java.lang.IllegalArgumentException: Can't find signing key in key ring.
        at com.verhas.licensor.License.loadKey(License.java:392)
        at com.verhas.licensor.License.loadKey(License.java:348)
        at com.verhas.licensor.License.loadKey(License.java:214)
        at License3j.encode(License3j.java:84)
        at License3j.main(License3j.java:170)

**Comment by holle** [comment]
I had the same problem and debugging showed that somehow the whitespace is a problem for the commandline args processor.
The --key="xxx (gfdsg) info@blabla.net" gets reduced to --key=xxx

Bummer :-(

call:
gpg --edit-key "xxx (gfdsg) info@blabla.net"
and run "adduid"
enter *just* a name w/o any blanks, no email, no comment.

Afterwards you can use the new uid to create licenses.

But beware! Both the checksum and the digest have changed.

- Cheers, Holger

**Comment by elmehdi-eljair** [comment]
Is there any solution to this problem. Because it makes this library not usable at all.

**Comment by verhas** [comment]
Use the operating system dependent space escaping. On Unix for example you can write 

```
--key=xxx\ gfdsg\ info...
```

If the program gets the arguments separated in the `public static void main(String[])` argument it can not do anything about it. It should not assume that two consecutive arguments are just one argument and glue them with space, because in that case there would be other mysterious errors.
