### ISSUE TITLE
HardwareBinder getMachineIdString() Hardware ID string changed even no hardware changed

### ISSUE THREAD

**Issue by tsatatwer** [verhas/License3j#39]
Hi,

I am using the license3j and using HardwareBinder getMachineIdString() method to get the hardware id as string BUT the id changed even if no hardware changed so I got deferent id values some times if the network disconnect to the router and connect again.

**Comment by verhas** [comment]
The hardware binder uses the JDK api available to query the interfaces as introduced in Java 5 (afair). When the OS changes what it reports the JDK and then License3j has no chance to see that the interfaces are the same. This is the best we can get.

My general recommendation is not to use the hardware binder because it is using an interface query that was designed for a different purpose and binding a license to a specific hardware is not a good idea in the first place.

The solution to your problem is not to bind the license to the hardware interfaces.

**Comment by tsatatwer** [comment]
OK , many thanks indeed for the fast support the issue can be closed.
