### ISSUE TITLE
Wrong command names in REPL application

### ISSUE THREAD

**Issue by Maurice22** [verhas/License3j#49]
The commands of the REPL application are all lower case (i.e. generatekeys instead of generateKeys), which is inconsistent with the "help" command output, as well as the readme.

**Comment by verhas** [comment]
The REPL application is case insensitive. Also, the one included in License3j v3.0.0 is a temporary solution. The long term target is to have the javax0.repl library and also the javax0.License3jrepl separate application. These are also available as snapshots in Github.

I see this issue more of a documentation shortage rather than a coding bug.

**Comment by Maurice22** [comment]
This seems not quite true, because the camel-case commands throw an error (i.e. [ERROR] command 'newLicense' is not defined). As you said, I started this issue to be primarily informative for other users. However, if this issue also exists in the new REPL application, I suggest to fix the documentation to prevent any inconvenience for new users.

**Comment by verhas** [comment]
I released 3.0.1 that fixes this issue. Please check, feedback and then I close the issue if you have no more comment.

**Comment by Maurice22** [comment]
Version 3.0.1 fixed the issue. Thanks for the quick response!
