### ISSUE TITLE
command 'generateKeys' is not defined

### ISSUE THREAD

**Issue by fengchangfight** [verhas/License3j#57]
I did as the doc said, just can't get through it, please help...

**Comment by fengchangfight** [comment]
I'm using jdk 11

**Comment by verhas** [comment]
Could you be more specific describing what the issue you are facing is? I suspect that you are reading the documentation of one version and using a different one. Have a look at the version tags and read the documentation of the version that you downloaded.

Note that the `master` branch does not contain the REPL functionality. In the non-released development version, the REPL functionality is implemented in a separate library so that you do not need to include the REPL into the application that verifies the license information.

**Comment by verhas** [comment]
I close the issue as I got no more information and a new release was crated in the meantime.
