### ISSUE TITLE
missing class

### ISSUE THREAD

**Issue by damianosky** [verhas/License3j#64]
In your home you describe the creation of a key pair through:

$ java -cp license3j-3.0.0.jar javax0.license3j.Repl

but in the jar i've downloaded, it does not exist the class.
It si somtheing missing or the docs are outdated?

Best regards

Damiano

**Comment by verhas** [comment]
I cannot find the line you are referring to.

There are two different programs that we can talk about. One is a library, `lincese3j`. The other one is an interactive tool called `license3jrepl`. The second program uses the first one and only the second can be started. The simplest way is to use the docker image

```
docker run -v `pwd`:/opt -ti license3jrepl:3.1.4
```

that will run the license manager in a docker container. If you want to run it in the host OS then you have to start it as

```
java -jar License3jrepl-3.1.1-jar-with-dependencies.jar
```

as it is in the `README.md` of https://github.com/verhas/License3jRepl

This line is outdated in the sense that the current version is 3.1.4 and I strongly recommend to use this version since there is a significant bug in prior versions that prevent many times the license load from the binary serialized format.
