### ISSUE TITLE
A new version with org.bouncycastle:bcprov-jdk15on v1.60 

### ISSUE THREAD

**Issue by tezcan10** [verhas/License3j#72]
Hi,
I am currently using version 2.0.0 from maven central repository in my application.
The tool snyk.com we use to check for any vulnerabilities marking License3j with the following two errors

  1) Insecure Encryption [High Severity][https://snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-32369] in org.bouncycastle:bcprov-jdk15on@1.57
  2) Deserialization of Untrusted Data [High Severity][https://snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-32412] in org.bouncycastle:bcprov-jdk15on@1.57

It indicates that both are introduced by com.verhas:license3j@2.0.0 > org.bouncycastle:bcpg-jdk15on@1.57 > org.bouncycastle:bcprov-jdk15on@1.57

And that this issue was fixed in versions: 1.60 of bcpg-jdk15on and bcprov-jdk15on dependencies of org.bouncycastle

Is there a  near future plans to prepare a new version of License3j that includes the version 1.60 of above artefacts of org.bouncycastle ?

Or
Can you tell me how I can prepare one in my own workspace?

Thanks in advance
Tezcan

**Comment by verhas** [comment]
Dear Tezcan,

I created a new 2.0.1 release. The difference between 2.0.0 and 2.0.1 is the dependency to BC to 1.60

Because the releases 2.x.x of License3j are outdated and legacy the support for them is limited.

I recommend migrating to the versions 3.x.x which does not have BC dependency. I understand and acknowledge that migration is not simple because the 3.x.x versions are not compatible to older versions. They use different API, different file formats, which means you have to reissue all licenses for the newer versions.

**Comment by tezcan10** [comment]
Dear Peter,
thank you so much for your prompt response and flexibility for creating a new version. Much appreciated

best regards
Tezcan

**Comment by tezcan10** [comment]
Dear Peter,
thank you for preparing the 2.0.1 release. I tried it out and have a tiny issue. Would you be able to compile it using jvm8 please? I have an old application and need the backward compatibility
Thnx in advance

**Comment by verhas** [comment]
I was afraid that you are going to ask that. It will take a bit more time than just this.

In the meantime, you could try to compile your application excluding the BC dependency from the License3j dependency and adding a new dependency to version 1.60 of BC on your application.

If you could try it, and could be so kind to inform me if that works it would be great. Since I did not need to change anything in the code from 2.0.0 to 2.0.1 the code should be compatible even on the JVM Level.

**Comment by tezcan10** [comment]
Dear Peter
Thanks for the tip.
Yes I did try and it worked with 1.7.0 but with 2.0.0 gives me class incompatible runtime error !!! Strange. I did not notice that yesterday. 

For the time being I can leave it like that at 1.7.0 but it would be great if you can get it for 2.0.1 soon

Best regards
Tezcan
