### ISSUE TITLE
Question - Warning updating from 1.0.4 to 2.0.1

### ISSUE THREAD

**Issue by dannyboyer** [verhas/License3j#73]
Hi!  I just updated from 1.0.4 to 2.0.1 and now get an illegal reflective access from BouncyCastle.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG 
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

I know you have a 3.x release without that dependency, but 2.0.1 is the latest I see on maven central.

Thanks!

**Comment by verhas** [comment]
>but 2.0.1 is the latest I see on maven central.

I understand that confusion. The groupId was changed. It is now

```xml
    <groupId>com.javax0.license3j</groupId>
    <artifactId>license3j</artifactId>
    <version>3.1.6-SNAPSHOT</version>
```

You can see that also in the `pom.xml`. I do not imply that you were supposed to recognize that. I will update the README to draw attention to that fact.

Btw: the illegal reflective access is not the cause of the License3j upgrade, rather than the same time you started to use a newer version of Java, presumably Java 9 or later. Java 9 introduced a Java Platform Module System that protects libraries and the JDK from illegal reflective access that was not meant by the developers.

Feel free to reopen this ticket if this answer does not help you or you need more help.

**Comment by dannyboyer** [comment]
Thanks @verhas I will try and update to v3, but before I do that, is there an upgrade path between v2 and v3 or is it completely different?

**Comment by verhas** [comment]
V3 is a complete rewrite of the old version. Also, the API and the types, and the license format were changed. Luckily the API is not too big. Therefore it should not be a lot of work to refactor the application to use the new version—the advantages of the simpler license handling and also the extensive API worth doing it.
