### ISSUE TITLE
License verification when adding a feature after signing.

### ISSUE THREAD

**Issue by Burtan** [verhas/License3j#74]
When I run the following code with 3.1.6 both asserts succeed. I thought the second one would fail?

```
val license = License()
license.add(Feature.Create.stringFeature("PRESIGN", "test"))
license.sign(keys.pair.private, "SHA-512")

assert(license.isOK(keys.pair.public))

license.add(Feature.Create.stringFeature("POSTSIGN", "test"))

assert(license.isOK(keys.pair.public))
```

**Comment by verhas** [comment]
Yes, it should.

Please fork, the repo, create a unit test that you think should fail but does not and I will look at it immediately.

**Comment by Burtan** [comment]
Thanks for the proposal. I then realized that my assert function did not work correctly. False alarm ;-). If you still want this test added to your suite, I can make a pull request. 
https://github.com/Burtan/License3j/blob/master/src/test/java/javax0/license3j/LicenseTest.java#L48

**Comment by verhas** [comment]
Since this is a bug in your code and not in License3j, there is no need. Thanks, and don't feel guilty for the false alarm. Better be safe than sorry. I had a guess that this was something with the assert, but I had no time to think about that, and your sample was not enough to try to reproduce.

Thanks.
