### ISSUE TITLE
how to migrate from 2 -> 3

### ISSUE THREAD

**Issue by rburgst** [verhas/License3j#75]
I currently use the 2.x version of license3j and have the public and private gpg key files. When trying to load these via the 3.1.2 repl (still on java 11) I get 

```
lprk  /Users/rainer/.gnupg/secring.gpg
java.security.NoSuchAlgorithmException: �TP� KeyFactory not available
	at java.base/java.security.KeyFactory.<init>(KeyFactory.java:138)
	at java.base/java.security.KeyFactory.getInstance(KeyFactory.java:183)
	at javax0.license3j.crypto.LicenseKeyPair$Create.getPrivateEncoded(LicenseKeyPair.java:197)
	at javax0.license3j.crypto.LicenseKeyPair$Create.from(LicenseKeyPair.java:164)
	at javax0.license3j.io.KeyPairReader.read(KeyPairReader.java:52)
	at javax0.license3j.io.KeyPairReader.readPrivate(KeyPairReader.java:46)
	at javax0.license3jrepl.App.loadPrivateKey(App.java:229)
	at javax0.repl.Repl.execute(Repl.java:388)
	at javax0.repl.Repl.run(Repl.java:342)
	at javax0.license3jrepl.App.main(App.java:132)
No license in memory
No keys in memory.
```

It would be nice to get a migration guide how to export the keys so that they can be used with the latest version.

**Comment by verhas** [comment]
# STATEMENT

There is no migration path to migrate existing keys from License3j version 2.x supported format to License3j version 3.x supported format.

The command-line application License3jRepl cannot load PGP formatted keys.

# FACTS

L3j v2 uses the Bouncy Castle library to read the keys and to perform encryption. This required the use of an external tool (GPG exactly) to create and manage keys. The dependency on an external library is always a maintenance cost. You should always consider the benefits the library use gives you versus the costs. Based on this assessment, I decided not to depend on the Bouncy library for version 3.x of L3j. The Bouncy Castle is a great library and can be a great value for projects. However, L3j used only a tiny subset of the functionality that did not justify the maintenance's extra hurdle.

L3j v3 can create their own keys and does not depend on any extra library. The format of the keys is different from PGP, and I decided not to support PGP keys or provide a tool to convert PGP keys to the L3j v3 proprietary format. Note also that the proprietary format is simply the run-length prefixed binary byte array of the key as it is. That way, the negative connotation that usually comes with the word "proprietary" should be taken with a pinch of salt.

# REASONING

The v2 and v3 versions of the application are not compatible with each other. They have different license, and key formats, as well as they, provide different APIs to support the same purpose. When an application moves from v2 to v3 it needs a total rewrite of the license handling module. The new version will not be able to read the old licenses or the old keys.

Most applications delivering a new version to the clients also provide new licenses free of charge or for an upgrade fee. In that case, the new license is delivered in the new format. Since the keys are just bytes and the actual byte content is not interpreted by the application there is no technical reason to use the old key in a new format when it has to be delivered to the clients. Security considerations also suggest replacing the keys from time to time. All this led to the decision not to invest effort into the development of a support tool that would convert the old PGP formatted public and private keys to the new format.

**Comment by rburgst** [comment]
Thanks a lot for the comprehensive answer. So I guess I will stick with v2 for the moment as re-issuing new certificates is currently not worthwhile for our project.
