### ISSUE TITLE
Using network interface names to calculate machine UUID downsides

### ISSUE THREAD

**Issue by vitomirs** [verhas/License3j#86]
Hello!

I am afraid that current way of calculating machine UUID using network adapter information is not really usable, at least with Windows OS. For example, after updating from Windows 10 21H1 to 21H2 my machine reports different UUID, which should not happen, doesn't it? That machine has only one hardware ethernet adapter, but Java reports total of 30 network adapters. And, by the way, for some reason non of them has virtual flag set, which means that all of them, with exception of one loopback interface, are used for UUID calculation. Few of these interfaces are Hyper-V virtual adapters (they also do not have virtual flag set (!?!)), and I can filter them out by using HardwareBinder.denied() method, but there are still 23 other interfaces used by License3j for UUID calculation. Only one of these interfaces has hardware address, I don't know what are for all of other interfaces, but that is not something specific to my computer, every Windows computer has many network interfaces not visible by user in Network settings.

In addition to hardware address, License3j uses names of all of these interfaces for MD5 hash calculation and then for UUID value. That does not seem like good approach to me, because Windows apparently changes number and/or names of these interfaces from time to time. I would use just hardware address without interface names in that calculation. I am not an expert on this subject, but I don't see it as more secure if, in addition, names are used.

**Comment by verhas** [comment]
I will look at it in a few days.

**Comment by Frotty** [comment]
Any update on this?

**Comment by verhas** [comment]
When you call the `UUIDCalculator::getMachineId` method you should have a `UUIDCalculator` instance. To create such an instance you should pass a `Network.Interface.Selector` object. This is a concrete, non-final, public class that gives you a lot of possibilities to filter the interfaces. If the method `usable()` returns true for a specific interface, then it will be included in the calculation, otherwise not.

The implementation in the class returns false if the interface is loop-back, virtual, or PPTP and it also checks two sets of strings using the strings as regular expressions and checking the names if they are allowed or denied. You can add individual strings to either of the sets calling `javax0.license3j.hardware.Network.Interface.Selector::interfaceAllowed` and `interfaceAllowed::interfaceDenied`.

I think that this gives enough flexibility, however, using Java OO features nothing stops you to extend the class `javax0.license3j.hardware.Network.Interface.Selector` and implement the functionality that you desire to select certain interface cards.
